version: "3"
services:
    mongo-db:
        container_name: mongo-container
        image: mongo
        restart: always
        volumes:
            - ./db:/data/db
        ports:
            - "27017:27017"
    api:
        container_name: conqueramazon-api
        build: ./conqueramazon-api
        restart: always
        volumes:
            - ./conqueramazon-api:/data
        environment:
            - DB_USERNAME: eugenDb
            - DB_NAME: shinytestdb
            - DB_PASSWORD: Mha1994mutin!
            - NODE_ENV: container
        depends_on: 
            - mongo-db
    app:
        container_name: conqueramazon-fe
        build: ./conquer-amz
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./conqueramazon-fe:/data
        environment:
            - BASE_API: http://localhost:3000
