version: "3"
services:
    app:
        container_name: seller-partner-container
        restart: always
        build: ./
        ports:
            - "80:3000"
        volumes:
            - .:/app
        links:
            - mongo
    mongo:
        container_name: mongo-container
        image: mongo
        ports:
            - "27017:27017"